language: java
jdk:
 - oraclejdk8
before_install:
  - chmod +x mvnw
cache:
  directories:
    - $HOME/.m2
addons:
  sonarcloud:
    organization: "magja"
    token:
      secure: "NNX64+2ZQr3jVIOKZfUXINTE8AqphvYYOMZL5zFoAxaAnUdLvwqHQ2Ai8lFBeJgHsjG4VvbMQ50ZK8h4EIZ7UTgaCEqDkdhXzyWkAgIYwW/P+6YYF+eU4BIXOzaKgpI1CNYbU7haE05o0Dhcz5qPMVGUPG0lhXAt8v50gyAw7WE="
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
script: ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
after_success:
 - bash <(curl -s https://codecov.io/bash)
